name = "datascope-dashboard"
main = "src/index.js"
compatibility_date = "2026-08-14"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "datascope"
database_id = "5c2aec29-5d83-4672-b352-99a1a2d42a6d"
