name = "external-domain-trust-dashboard"
main = "src/index.js"
compatibility_date = "2026-08-14"
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "datascope"
database_id = "de2f429f-121d-4649-ab07-5126123a864e"
